version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment: &ENVIRONMENT
          DOCKER_IMAGE_NAME: decentraland/communications

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: make installci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: make testci LINK_PREFIX=sudo

  build-image:
    docker:
      - image: circleci/node:10
        environment: *ENVIRONMENT

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - setup_remote_docker: { docker_layer_caching: true }

      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 .

      - run: &LOGIN_DOCKER
          name: Log in DockerHub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

      - run:
          name: Push to DockerHub
          command: docker push "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1"

  deploy-staging:
    docker:
      - image: circleci/node:10
        environment: *ENVIRONMENT

    working_directory: ~/repo

    steps:

      - setup_remote_docker: { docker_layer_caching: true }

      - run: *LOGIN_DOCKER

      - run:
          name: Tag docker image
          command: |
            docker tag $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 $DOCKER_IMAGE_NAME:next

      - run:
          name: Deploy
          command: |
            echo 'deploy $DOCKER_IMAGE_NAME:$CIRCLE_SHA1'

  deploy-prod:
    docker:
      - image: circleci/node:10
        environment: *ENVIRONMENT

    working_directory: ~/repo

    steps:
      - setup_remote_docker: { docker_layer_caching: true }

      - run: *LOGIN_DOCKER

      - run:
          name: Tag docker image
          command: |
            docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1" "$DOCKER_IMAGE_NAME:$CIRCLE_TAG"

      - run:
          name: Deploy
          command: |
            echo 'deploy $DOCKER_IMAGE_NAME:$CIRCLE_SHA1'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - build-image:
          requires:
            - build

      - deploy-staging:
          requires:
            - build-image
          filters:
            branches:
              only: master

      - deploy-prod:
          requires:
            - build-image
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
