version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "packages/server/package-lock.json" }}-{{ checksum "packages/client/package-lock.json" }}-{{ checksum "packages/protocol/package-lock.json" }}

      - run: make installci

      - save_cache:
          paths:
            - node_modules
            - packages/server/node_modules
            - packages/client/node_modules
            - packages/protocol/node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "packages/server/package-lock.json" }}-{{ checksum "packages/client/package-lock.json" }}-{{ checksum "packages/protocol/package-lock.json" }}

      - run: make devlink GLOBAL_LINK_PREFIX=sudo

      - run: make test
